### ISSUE TITLE
Suppress error logging when needed

### ISSUE THREAD

**Issue by vipinnair22** [mattlewis92/webpack-retry-chunk-load-plugin#10]
Hello,

I'm using this plugin to refresh the page whenever chunk load fails. I have configured the last resort step to do something like this.

```
  new RetryChunkLoadPlugin({
        maxRetries: 3,
        lastResortScript: `window.chunkLoadFailed = true; 
                           window.location.reload(true)`
      })
```
The `window.chunkLoadFailed` piece of code is being used for logging my custom event and we don't want to log an actual error when this happens. I'm wondering if it's possible to suppress error logging if needed. Thanks!

**Comment by mattlewis92** [comment]
Hey there, you could override the onerror handler and use that to filter out the error message: https://stackoverflow.com/a/7133529 This is the only way I can think of to do it, as the script chunk loading error comes from the browser itself and not from anything this plugin does. Hope that helps!
