### ISSUE TITLE
Not compatible with webpack5?

### ISSUE THREAD

**Issue by appzuka** [mattlewis92/webpack-retry-chunk-load-plugin#11]
I had to remove webpack-retry-chunk-load-plugin after upgrading to webpack 5.  I was getting errors that 'jsonpScriptSrc' is not defined.

**Comment by mattlewis92** [comment]
Looks like there are definitely a lot of changes in webpack 5 in the way that [scripts are loaded](https://github.com/webpack/webpack/blob/master/lib/web/JsonpChunkLoadingRuntimeModule.js) that would break this module, PRs welcome with a fix!

**Comment by ricky11** [comment]
Version 1.5 for webpack 4?
