### ISSUE TITLE
Cannot read property 'getChunkScriptFilename' of undefined

### ISSUE THREAD

**Issue by alireza-mh** [mattlewis92/webpack-retry-chunk-load-plugin#14]
Hi there,

I get `Cannot read property 'getChunkScriptFilename' of undefined` while I'm adding `webpack-retry-chunk-load-plugin` to the project.
I use react loadable and implemented dynamic import like below with chunk name:

```
const AsyncRoutes = Loadable({
  loader: () => import(/* webpackChunkName: 'AsyncRoutes' */ 'src/routes/MyRoute'),
  loading() {
    return <Loader />;
  },
});
```
my plugin configuration: 
```
new RetryChunkLoadPlugin({
      cacheBust: `function() {
      return Date.now();
    }`,
      maxRetries: 2
    })
``` 
webpack: 4.44.1
webpack-cli: 3.3.12
webpack-retry-chunk-load-plugin: 2.0.0

wonder if I am missing something.

**Comment by mattlewis92** [comment]
Hey there, v2 of this plugin requires webpack 5 or higher, I think if you do `npm i webpack-retry-chunk-load-plugin@1` it will work ok.

**Comment by alireza-mh** [comment]
nice to know I thought so since the last update was 11 days ago and it was indicated that it's a dependency update I didn't bother to downgrade. my bad.
sorry to bother you and thanks for this package and you're a quick response.
