### ISSUE TITLE
Does the chunks option work with webpack 5?

### ISSUE THREAD

**Issue by aadisriram** [mattlewis92/webpack-retry-chunk-load-plugin#15]
Looks like the chunks option is no longer used and all chunks get the retry logic regardless of the option being supplied.

https://github.com/mattlewis92/webpack-retry-chunk-load-plugin/commit/cd6c7a59b4a6293982f1329295880df6be7ee1c7#diff-bfe9874d239014961b1ae4e89875a6155667db834a410aaaa2ebe3cf89820556L92-L114

I was trying this out with a Webpack 4 project (using v1.0.2) and I noticed that regardless of which chunk is missing I always end up on the page specified in the lastResortScript. I was going through that code when I noticed that in the latest master chunks passed in the options is not used.

**Comment by mattlewis92** [comment]
Oh yes it does look like the `chunks` option was removed, @salzhrani would you mind taking a look at this please? This was [how the logic from v1 worked](https://github.com/mattlewis92/webpack-retry-chunk-load-plugin/blob/v1/src/index.js#L103-L107), I'm not too sure how you can get the current chunk name in the updated webpack api.

**Comment by salzhrani** [comment]
Sorry for missing that. PR sent

**Comment by mattlewis92** [comment]
Released in `2.0.1`, thank you @salzhrani for the super quick turnaround! 😄
