### ISSUE TITLE
[Feature] Add timeout option

### ISSUE THREAD

**Issue by Amraneze** [mattlewis92/webpack-retry-chunk-load-plugin#17]
Hi,

It would be good to have a timeout option that would be set 0 by default. Sometimes, users have some network issues for some seconds (Anti-virus, proxy, too many requests, ...) that can be solved just by waiting a little before importing the chunk. Let me know your point of view 

Thank you

**Comment by mattlewis92** [comment]
Sounds like a good idea to me, would you like to make a pull request with the change?

**Comment by Amraneze** [comment]
I will start working on it
