### ISSUE TITLE
No given timeout results into `undefined` as second parameter of `setTimeout`

### ISSUE THREAD

**Issue by jens-duttke** [mattlewis92/webpack-retry-chunk-load-plugin#27]
After checking the change in 2.1.0 I saw that it will result into the following code:
```
setTimeout(function () { [...] }, undefined);
```
Or minified:
```
setTimeout((function(){ [...] }),void 0)
```

This does not result into an error, but strictly speaking, `undefined` is an invalid value, since `setTimeout` expect a number here.
Either way, it is wasted characters in the minified file.

Beside that, the code looks like a "delay" (as the commit message states), instead of a "timeout" (even if it uses `setTimeout`), so the option name is misleading.

**Comment by mattlewis92** [comment]
Oh yeah you're totally right, and that name is quite confusing, something like `retryDelay` would probably be better. Do you want to send a PR that changes it to something like `options.retryDelay || options.timeout || 0` and we can just deprecate the `timeout` option but keep it there for backwards compat 😄
