### ISSUE TITLE
Support for custom/multiple retries via params

### ISSUE THREAD

**Issue by Aqours** [mattlewis92/webpack-retry-chunk-load-plugin#4]
Support for custom/multiple retries via params(maybe we need retry_interval param too) and loaded error callback for reporting errors

**Comment by mattlewis92** [comment]
That sounds like a good idea, would you like to make a pull request?

**Comment by ayushya** [comment]
I have raised a PR for this issue [here](https://github.com/mattlewis92/webpack-retry-chunk-load-plugin/pull/5)
