### ISSUE TITLE
Doesn't seem to be running in "prod"

### ISSUE THREAD

**Issue by dac09** [mattlewis92/webpack-retry-chunk-load-plugin#9]
Hi, thanks for building this.

I've setup the plugin, and it works beautifully when running my project in dev, but doesn't seem to do anything when packaged as a dist build. I can definitely see the plugin in my plugins list when packaging.

Any tips?

**Comment by mattlewis92** [comment]
Hey there, sorry to hear you're having issues. In prod the contents of this plugin should be extracted into the runtime chunk and not the main one which might be why you're not seeing it show up in the dist files. If you can give me instructions on how to setup your PR locally I can try and debug and see what's going on? Thanks! 😄

**Comment by dac09** [comment]
Hey thanks for the reply! Because the PR is into the redwood framework itself, maybe it'll be easier if I setup a project with redwood to repro the issue? 

Let me know if you want to try running RW anyway, happy to provide instructions if you're curious!

**Comment by dac09** [comment]
Hi Matt, in the process of creating a repro for you, it seems to me that the plugin is working fine in a clean new project. It might be something in the setup of my original project.

Closing this for now, will ping again if I find the issue on the specific project.
